config/routes.rb
Rails.application.routes.draw do
  resources :visitors, except: [:index, :new, :create, :show]
  get 'setup/index'
  match '/setup', to: 'setup#index', via: [:get, :post]
  match '/authentication_setup', to: 'settings#authentication', via: [:get, :post]
  resources :people
  get 'visitor_log/index'
  get '/visitor_log', to: 'visitor_log#index'
  get '/visitor_log_all', to: 'visitor_log#visitor_log_all'
  get 'admin', to: 'visitor_log#admin'
  get 'visitor_log/:action', controller: 'visitor_log'
  resources :companies
  resources :reasons

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }
  resources :employees, path: :persons, except: [:edit] do
    member do
      get 'log_in'
    end
    get 'home/index', as: 'home'
  end

  resources :users, only: [:index, :show, :destroy] do
    collection do
      match 'recently_connected', via: [:post, :get]
      match 'active', via: [:post, :get]
      match 'audit', via: [ :get]
    end
    member do
      get 'require_change_password'
      get 'restore'
      get 'lock'
      get 'unlock'
      put 'change_password'
      put 'change_basic_info'
      put 'attachments'
      post 'image_upload'
      get 'remove_image'
    end


  end


  root to: 'welcome#visitors'

  match '/create_visitor', to: 'welcome#create_visitor', via: [:get, :post]
  match '/recognize_visitor', to: 'welcome#recognize_visitor', via: [:get, :post]

  get '/check_email', to: 'welcome#check_email'
  match '/update_visitor', to: 'welcome#update_visitor', via: [:post, :get]
  post '/update_visitor_visit', to: 'welcome#update_visitor_visit'
  post '/get_visitor_info', to: 'welcome#get_visitor_info'
  get '/visitors', to: 'welcome#visitors'
  get '/visitor_bye', to: 'welcome#visitor_bye'
  match '/visitor_signout', to: 'welcome#visitor_signout', via: [:get, :post]
  match '/check_visitor', to: 'welcome#check_visitor', via: [:get, :post]
  get '/visitor_sign_form', to: 'welcome#visitor_sign_form'
  get '/visitor_badge', to: 'welcome#visitor_badge'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :admin_login_pages, only: :index do
    collection do
      post :update
    end
  end
  resources :social_keys, only: [:new,:create]
end

app/controllers/employees_controller.rb
class EmployeesController < BaseController
  before_action  :authenticate_user!
  before_action  :set_employee, :only => [:show, :destroy, :log_in, :update]
  before_action  :authorize
  # include UserProfilesHelper
  include ApplicationHelper

  def index
    respond_to do |format|
      format.html{}
      format.json{
        options = Hash.new
        options[:status_type] = params[:status_type]
        render json: EmployeeDatatable.new(view_context,options)
      }
    end
  end

  def show
    redirect_to '/profile_record'
  end

  def new
    # r = Role.where(role_type_id: RoleType.default.try(:id)).first
    @user = User.new()
    # @user.core_demographic = CoreDemographic.new
    # @user.job_detail = JobDetail.new
  end

  def create
    @user = User.new(params.require(:user).permit(employee_params))
    if @user.save
      # UserMailer.welcome_email(@user, params[:user][:password]).deliver_later
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    if @employee.update(params.require(:user).permit(User.safe_attributes))
      flash[:notice] = I18n.t('notice_successful_update')
    else
      flash[:error] =  @employee.errors.full_messages.join('<br/>')
    end
    redirect_to employee_path(@employee)
  end

  def destroy
    session[:employee_id] = nil
    # flash[:notice]= "Logged Off from #{@employee.login}"
    redirect_to root_path
  end

  private

  def set_employee
    @employee = User.find params[:id]
    raise Unauthorized if @employee.admin? and !User.current.admin?
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize
    raise Unauthorized unless User.current.admin?
  end

  def employee_params
   User.safe_attributes
  end

  def random_email(params)
    core_params = params[:user][:core_demographic_attributes] ||  {}
    "#{core_params[:first_name]||'user'}.#{core_params[:last_name]}#{rand(252...4350)}#{User.count}@account.com"
  end
end

app/views/employees/_list.html.erb
<table class="display  projects-table table  table-striped  table-hover" cellspacing="0" width="100%" id="users_table">
  <thead>
  <tr>
    <th>#</th>
    <th><%= t 'profile.first_name' %></th>
    <th><%= t 'profile.middle_name' %></th>

    <th><%= t 'profile.last_name' %></th>
    <th><%= t 'profile.gender' %></th>
    <th><%= t :email %></th>

    <th><%= t 'profile.birthday' %></th>
    <th><%= 'Organization' %>
    <th><%= 'Active' %></th>

  </tr>
  </thead>

  <tbody>

  </tbody>
  <tfoot>

  </tfoot>
</table>
<script>
  $(document).ready(function(){
    var table = $('#users_table').DataTable({
      "ajax": "<%= employees_path(format: :json, status_type: params[:status_type]) %>",
      processing: true,
      serverSide: true,
      responsive: true,
      display: [[0, 'asc']],
      "bDestroy": true,
      "columns": [
        { "searchable": true, "orderable": true },
        { "searchable": true, "orderable": true },
        { "searchable": true, "orderable": true },

        { "searchable": true, "orderable": true },
        { "searchable": true, "orderable": true },
        { "searchable": true, "orderable": true },

        { "searchable": true, "orderable": true },
        { "searchable": true, "orderable": true },
        { "searchable": false, "orderable": false }
      ],
      "sDom": "<'dt-toolbar'" +
      "<'col-sm-5 col-xs-8'f>" + //search box
      "<'col-sm-2 col-sm-offset-4 col-xs-2 'C>"+// drop down size
      "<'col-sm-1 col-xs-2 'l>>"+// drop down size
      "t"+ // the table
      "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
      "iDisplayLength": 10
    })
  } );
</script>

app/views/employees/_new.html.erb
<%= form_for(user, url: employees_path, html: { method: :post, class: 'form-horizontal', id: 'smart-form-register' }) do |f| %>

    <fieldset>
      <legend><%#= t('change_employee_info') %></legend>
      <% if user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <label class="col-md-2 control-label">Full name</label>
        <div class="col-md-9">
          <%= f.text_field :full_name, placeholder: 'Full name' , class: 'form-control' %>
        </div>
      </div>


      <div class="form-group email_div">
        <label class="col-md-2 control-label"><%= t(:email) %></label>
        <div class="col-md-9">
          <%= f.email_field :email, placeholder: 'Email' , class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">automatic password generation</label>
        <div class="col-md-9">
          <%= check_box_tag :auto_password, true, '1' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label"><%= t('profile.password') %></label>
        <div class="col-md-9">
          <%= f.password_field :password, autocomplete: "off", placeholder: 'Password' , class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label"><%= t('profile.password_confirmation') %></label>
        <div class="col-md-9">
          <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Password confirmation' , class: 'form-control' %>
        </div>
      </div>


      <% if User.current.admin? %>
          <div class="form-group">
            <label class="col-md-2 control-label">Administrator</label>
            <div class="col-md-9">
              <%= f.check_box :admin %>
            </div>
          </div>
       <div class="form-group">
            <label class="col-md-2 control-label">Active </label>
            <div class="col-md-9">
              <%= f.check_box :state %>
            </div>
          </div>
      <% end %>



      <div class="form-group" >
        <div class="col-md-11">
         <%= link_to  'Cancel', :back, class: 'btn btn-warning pull-right' %>
         <%= f.submit 'Create', class: 'btn btn-success pull-right' %>
        </div>
      </div>
    </fieldset>
<% end %>
<script>
  // Validation
  $(function() {
    runAllForms();
    // Validation
    $("#smart-form-register").validate({

      // Rules for form validation
      rules : {
        "user[full_name]" : {
          required : true
        },
        "user[email]" : {
          required : true
        },
        "user[password]" : {
          required : true,
            minlength: 6,

        },
        "user[password_confirmation]" : {
          required : true,
            minlength: 6,
            equalTo: "#user_password"
        },
      },
      // Do not change code below
      errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
      }
    });

    $('#auto_password').on('change', function(){
      generate_random_password()
    })
    generate_random_password()
  });

  function generate_random_password(){
    str ='';
    if($('#auto_password').prop('checked'))
    {
      str = 'A'+ Math.random().toString(36)
    }
    $('#user_password').val(str);
    $('#user_password_confirmation').val(str);
  }
</script>

app/views/employees/index.html.erb
<section id="widget-grid" class="user_account">
  <div class="module-title">
    <h2 class='module-title-text'>SEARCH CLIENT</h2>
  </div>
  <div class="col-xs-12 btn-edition tabs-section">
    <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle filter-tab" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FILTER <span class="caret"></span></button>
      <ul class="dropdown-menu dropdown-links" role="menu">
        <li>
          <span class="glyphicon glyphicon-asterisk"></span>
          <%= link_to 'All', {}.merge(status_type: 'all'), class: 'dropdown-item'  %>
        </li>
        <div class='dropdown-item-dividier'></div>
        <li>
          <span class="glyphicon glyphicon-ok-circle"></span>
          <%= link_to 'Active', {}.merge(status_type: 'active'), class: 'dropdown-item'  %>
        </li>
        <div class='dropdown-item-dividier'></div>
        <li>
          <span class="glyphicon glyphicon-ban-circle"></span>
          <%= link_to 'Inactive', {}.merge(status_type: 'inactive'), class: 'dropdown-item'  %>
        </li>
      </ul>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle actions-tab" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ACTIONS <span class="caret"></span></button>
      <ul class="dropdown-menu dropdown-links" role="menu">
        <li>
          <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
          <%= link_to t(:new_employee), new_employee_path, class: 'dropdown-item' %>
        </li>
          <div class='dropdown-item-dividier'></div>
        <li>
          <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
          <%= link_to 'Print', params.permit(:from, :to, :status_type).merge(format: 'pdf'), class: 'dropdown-item'  %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'list',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     wid_id: 'clients',
                     wid_title: t('employees')
                 } %>
    </article>
  </div>
</section>

app/views/employees/new.html.erb
<section id="widget-grid" class="new_user_account">
  <div class="row">
    <article class="col-xs-12">
      <%= render partial: 'new',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     wid_id: 'new_user',
                     wid_title: 'New user',
                     user: @user
                 } %>
    </article>
  </div>
</section>

app/views/employees/show.html.erb
<%= render_tabs user_profiles_tab %>